-- MySQL Script generated by MySQL Workbench
-- 03/20/15 22:29:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema apteka
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema apteka
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `apteka` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `apteka` ;

-- -----------------------------------------------------
-- Table `apteka`.`Roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apteka`.`Roles` ;

CREATE TABLE IF NOT EXISTS `apteka`.`Roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apteka`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apteka`.`Users` ;

CREATE TABLE IF NOT EXISTS `apteka`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_id` INT NULL,
  `login` VARCHAR(45) NOT NULL,
  `full_name` VARCHAR(120) NOT NULL,
  `hash` VARCHAR(120) NOT NULL,
  `salt` VARCHAR(15) NOT NULL,
  `address` VARCHAR(150) NOT NULL,
  `medical_policy_number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Users_Roles_idx` (`role_id` ASC),
  CONSTRAINT `fk_Users_Roles1`
  FOREIGN KEY (`role_id`)
  REFERENCES `apteka`.`Roles` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apteka`.`Recipes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apteka`.`Recipes` ;

CREATE TABLE IF NOT EXISTS `apteka`.`Recipes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `created_at` DATE NOT NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apteka`.`Drugs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apteka`.`Drugs` ;

CREATE TABLE IF NOT EXISTS `apteka`.`Drugs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT 'Название лекарства',
  `description` MEDIUMTEXT NOT NULL COMMENT 'Описание лекарства',
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apteka`.`Diagnoses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apteka`.`Diagnoses` ;

CREATE TABLE IF NOT EXISTS `apteka`.`Diagnoses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `patient_user_id` INT NOT NULL COMMENT 'Идентификатор пациента',
  `doctor_user_id` INT NULL COMMENT 'Идентификатор доктора',
  `recipe_id` INT NULL,
  `diagnosis` VARCHAR(200) NOT NULL COMMENT 'Диагноз врача',
  `complaints` VARCHAR(200) NOT NULL COMMENT 'Жалобы пациента',
  `created_at` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Diagnoses_Recipes_idx` (`recipe_id` ASC),
  INDEX `fk_Diagnoses_Patient_Users_idx` (`patient_user_id` ASC),
  INDEX `fk_Diagnoses_Doctor_Users_idx` (`doctor_user_id` ASC),
  CONSTRAINT `fk_Diagnoses_Patient_Users`
  FOREIGN KEY (`patient_user_id`)
  REFERENCES `apteka`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Diagnoses_Recipes`
  FOREIGN KEY (`recipe_id`)
  REFERENCES `apteka`.`Recipes` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Diagnoses_Doctor_Users`
  FOREIGN KEY (`doctor_user_id`)
  REFERENCES `apteka`.`Users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apteka`.`drug_progress_statuses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apteka`.`drug_progress_statuses` ;

CREATE TABLE IF NOT EXISTS `apteka`.`drug_progress_statuses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apteka`.`recipes_has_drugs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apteka`.`recipes_has_drugs` ;

CREATE TABLE IF NOT EXISTS `apteka`.`recipes_has_drugs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `recipe_id` INT NOT NULL,
  `drug_id` INT NOT NULL,
  `progress_status_id` INT NULL COMMENT 'Статус готовности лекарства',
  `count` INT NOT NULL DEFAULT 1 COMMENT 'Количество лекарства',
  PRIMARY KEY (`id`),
  INDEX `fk_recipes_has_drugs_Drugs_idx` (`drug_id` ASC),
  INDEX `fk_recipes_has_drugs_Recipes_idx` (`recipe_id` ASC),
  INDEX `fk_recipes_has_drugs_drug_progress_statuses_idx` (`progress_status_id` ASC),
  CONSTRAINT `fk_Recipes_has_Drugs_Recipes1`
  FOREIGN KEY (`recipe_id`)
  REFERENCES `apteka`.`Recipes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Recipes_has_Drugs_Drugs1`
  FOREIGN KEY (`drug_id`)
  REFERENCES `apteka`.`Drugs` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_recipes_has_drugs_drug_progress_statuses1`
  FOREIGN KEY (`progress_status_id`)
  REFERENCES `apteka`.`drug_progress_statuses` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apteka`.`Materials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apteka`.`Materials` ;

CREATE TABLE IF NOT EXISTS `apteka`.`Materials` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT 'Название вещества',
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apteka`.`Ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apteka`.`Ingredients` ;

CREATE TABLE IF NOT EXISTS `apteka`.`Ingredients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `drug_id` INT NOT NULL,
  `material_id` INT NOT NULL,
  `count` INT NOT NULL COMMENT 'Кол-во вещества, необходимого для приготовления лекарства',
  PRIMARY KEY (`id`),
  INDEX `fk_Drugs_has_Materials_Materials1_idx` (`material_id` ASC),
  INDEX `fk_Drugs_has_Materials_Drugs1_idx` (`drug_id` ASC),
  CONSTRAINT `fk_Drugs_has_Materials_Drugs1`
  FOREIGN KEY (`drug_id`)
  REFERENCES `apteka`.`Drugs` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Drugs_has_Materials_Materials1`
  FOREIGN KEY (`material_id`)
  REFERENCES `apteka`.`Materials` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apteka`.`storehouse_inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apteka`.`storehouse_inventory` ;

CREATE TABLE IF NOT EXISTS `apteka`.`storehouse_inventory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `material_id` INT NOT NULL,
  `count` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_storehouse_inventory_Materials1_idx` (`material_id` ASC),
  CONSTRAINT `fk_storehouse_inventory_Materials1`
  FOREIGN KEY (`material_id`)
  REFERENCES `apteka`.`Materials` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
  ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
