-- MySQL Script generated by MySQL Workbench
-- 03/20/15 22:29:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Roles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_id` INT NULL,
  `login` VARCHAR(45) NOT NULL,
  `full_name` VARCHAR(120) NOT NULL,
  `hash` VARCHAR(120) NOT NULL,
  `salt` VARCHAR(15) NOT NULL,
  `address` VARCHAR(150) NOT NULL,
  `medical_policy_number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Users_Roles_idx` (`role_id` ASC),
  CONSTRAINT `fk_Users_Roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`Roles` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recipes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Recipes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Recipes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `created_at` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Drugs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Drugs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Drugs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT 'Название лекарства',
  `description` MEDIUMTEXT NOT NULL COMMENT 'Описание лекарства',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Diagnoses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Diagnoses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Diagnoses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `patient_user_id` INT NOT NULL COMMENT 'Идентификатор пациента',
  `doctor_user_id` INT NULL COMMENT 'Идентификатор доктора',
  `recipe_id` INT NULL,
  `diagnosis` VARCHAR(200) NOT NULL COMMENT 'Диагноз врача',
  `complaints` VARCHAR(200) NOT NULL COMMENT 'Жалобы пациента',
  `created_at` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Diagnoses_Recipes_idx` (`recipe_id` ASC),
  INDEX `fk_Diagnoses_Patient_Users_idx` (`patient_user_id` ASC),
  INDEX `fk_Diagnoses_Doctor_Users_idx` (`doctor_user_id` ASC),
  CONSTRAINT `fk_Diagnoses_Patient_Users`
    FOREIGN KEY (`patient_user_id`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Diagnoses_Recipes`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `mydb`.`Recipes` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Diagnoses_Doctor_Users`
    FOREIGN KEY (`doctor_user_id`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DrugProgressStatuses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DrugProgressStatuses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DrugProgressStatuses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RecipesHasDrugs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`RecipesHasDrugs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`RecipesHasDrugs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `recipe_id` INT NOT NULL,
  `drug_id` INT NOT NULL,
  `progress_status_id` INT NULL COMMENT 'Статус готовности лекарства',
  `count` INT NOT NULL DEFAULT 1 COMMENT 'Количество лекарства',
  PRIMARY KEY (`id`),
  INDEX `fk_RecipesHasDrugs_Drugs_idx` (`drug_id` ASC),
  INDEX `fk_RecipesHasDrugs_Recipes_idx` (`recipe_id` ASC),
  INDEX `fk_RecipesHasDrugs_DrugProgressStatuses_idx` (`progress_status_id` ASC),
  CONSTRAINT `fk_Recipes_has_Drugs_Recipes1`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `mydb`.`Recipes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Recipes_has_Drugs_Drugs1`
    FOREIGN KEY (`drug_id`)
    REFERENCES `mydb`.`Drugs` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_RecipesHasDrugs_DrugProgressStatuses1`
    FOREIGN KEY (`progress_status_id`)
    REFERENCES `mydb`.`DrugProgressStatuses` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Materials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Materials` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Materials` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT 'Название вещества',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ingredients` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ingredients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `drug_id` INT NOT NULL,
  `material_id` INT NOT NULL,
  `count` INT NOT NULL COMMENT 'Кол-во вещества, необходимого для приготовления лекарства',
  PRIMARY KEY (`id`),
  INDEX `fk_Drugs_has_Materials_Materials1_idx` (`material_id` ASC),
  INDEX `fk_Drugs_has_Materials_Drugs1_idx` (`drug_id` ASC),
  CONSTRAINT `fk_Drugs_has_Materials_Drugs1`
    FOREIGN KEY (`drug_id`)
    REFERENCES `mydb`.`Drugs` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Drugs_has_Materials_Materials1`
    FOREIGN KEY (`material_id`)
    REFERENCES `mydb`.`Materials` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StorehouseInventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`StorehouseInventory` ;

CREATE TABLE IF NOT EXISTS `mydb`.`StorehouseInventory` (
  `id` INT NOT NULL,
  `material_id` INT NOT NULL,
  `count` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_StorehouseInventory_Materials1_idx` (`material_id` ASC),
  CONSTRAINT `fk_StorehouseInventory_Materials1`
    FOREIGN KEY (`material_id`)
    REFERENCES `mydb`.`Materials` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
